"""The `tour` flow: from an entry point outward through the import graph, one
stop per file, each with an explanation and one question."""

import re
from collections import Counter
from pathlib import Path

from plumb.engine import prompts
from plumb.engine.citations import strip_citations
from plumb.engine.frontend import AskChoice, Info, Status
from plumb.engine.plan import PlanSession
from plumb.engine.schemas import Question
from plumb.memory.tour import TourProgress, load_tours, save_tours
from plumb.repomap.builder import build_repo_map, save_summary
from plumb.repomap.entry_points import is_test_file
from plumb.repomap.model import RepoMap

STOPS_PER_LEG = 5
MAX_ENTRY_CHOICES = 8
MAX_SUMMARY_CHARS = 400
MANIFEST_REASONS = ("pyproject", "package.json", "pubspec")


GENERATED_NAME = re.compile(
    r"(^|/)generated_[^/]*$|\.g\.dart$|\.freezed\.dart$|\.pb\.go$|_pb2\.py$|\.generated\.\w+$"
)
GENERATED_HEADER = re.compile(
    r"generated file|do not edit|@generated|auto-?generated|generated by", re.IGNORECASE
)
HEADER_LINES = 10


def is_generated(root: Path, rel: str) -> bool:
    """A generated-style name, or a header comment that says it was generated."""
    if GENERATED_NAME.search(rel):
        return True
    try:
        with (root / rel).open(encoding="utf-8", errors="replace") as handle:
            head = "".join(handle.readline() for _ in range(HEADER_LINES))
    except OSError:
        return False
    return bool(GENERATED_HEADER.search(head))


def entry_choices(repo_map: RepoMap, root: Path) -> list[str]:
    """Entry points worth starting from: manifest-backed first; no tests and
    no generated files."""
    entries = [
        e
        for e in repo_map.entry_points
        if not is_test_file(e.path) and not is_generated(root, e.path)
    ]

    def rank(reason: str) -> int:
        if any(m in reason for m in MANIFEST_REASONS):
            return 0
        return 1 if "file name" in reason else 2

    entries.sort(key=lambda e: (rank(e.reason), e.path))
    return [e.path for e in entries][:MAX_ENTRY_CHOICES]


def route(repo_map: RepoMap, start: str, visited: set[str]) -> list[str]:
    """Breadth-first from `start` along imports; at each step the files that
    many others import (the core) come first. Tests and visited files are left out."""
    importers = Counter(
        t for targets in repo_map.import_graph.values() for t in targets
    )
    order: list[str] = []
    seen = set(visited)
    frontier = [start]
    while frontier:
        next_frontier: list[str] = []
        for path in frontier:
            if path in seen or path not in repo_map.files or is_test_file(path):
                continue
            seen.add(path)
            order.append(path)
            targets = sorted(
                repo_map.import_graph.get(path, []), key=lambda t: (-importers[t], t)
            )
            next_frontier += [t for t in targets if t not in seen]
        frontier = next_frontier
    return order


def first_paragraph(text: str) -> str:
    paragraph = next((p.strip() for p in text.split("\n\n") if p.strip()), "")
    paragraph = strip_citations(paragraph)
    return paragraph[:MAX_SUMMARY_CHARS]


class TourFlow:
    def __init__(self, session: PlanSession) -> None:
        self.session = session

    async def run(self, start: str | None = None) -> None:
        s = self.session
        s.recorder.start("tour")
        s.recorder.log("request", text=f"/tour {start or ''}".strip())
        root = s.toolbox.scope.root
        repo_map = build_repo_map(root, s.tutor_dir, s.recorder.now())
        s.toolbox.refresh(repo_map)

        if start is None:
            start = await self._pick_entry(repo_map)
            if start is None:
                s._finish()
                return
        else:
            start = start.strip().removeprefix("./")
            if start not in repo_map.files:
                s.frontend.emit(Info(f"`{start}` isn't a file I can see in this repo."))
                s._finish()
                return

        tours = load_tours(s.tutor_dir)
        progress = tours.tours.get(start)
        if progress and progress.queue:
            answer = await s.frontend.ask(
                AskChoice(
                    f"You toured {len(progress.visited)} stops from {start} before.",
                    [f"Resume ({len(progress.queue)} stops left)", "Start over"],
                )
            )
            if answer.kind != "option":
                s._finish()
                return
            if answer.option == 2:
                progress = None
        if not progress or not progress.queue:
            progress = TourProgress(
                visited=[],
                queue=route(repo_map, start, set()),
                updated_at=s.recorder.now(),
            )
        s.recorder.log(
            "tour", start=start, queue=progress.queue, visited=progress.visited
        )
        s.frontend.emit(
            Info(f"Touring from `{start}`: {len(progress.queue)} stops on this route.")
        )

        came_from = progress.visited[-1] if progress.visited else None
        stops_this_leg = 0
        while progress.queue:
            if stops_this_leg == STOPS_PER_LEG:
                answer = await s.frontend.ask(
                    AskChoice("Continue the tour?", ["Continue", "Stop here"])
                )
                if answer.kind != "option" or answer.option != 1:
                    break
                stops_this_leg = 0
            path = progress.queue.pop(0)
            await self._stop(path, came_from, len(progress.visited) + 1)
            progress.visited.append(path)
            progress.updated_at = s.recorder.now()
            tours.tours[start] = progress
            save_tours(s.tutor_dir, tours)
            came_from = path
            stops_this_leg += 1
        if not progress.queue:
            s.frontend.emit(Info("That's the end of this route."))
        else:
            s.frontend.emit(
                Info(
                    f"Tour paused; `/tour {start}` resumes ({len(progress.queue)} stops left)."
                )
            )
        s._finish()

    async def _pick_entry(self, repo_map: RepoMap) -> str | None:
        s = self.session
        choices = entry_choices(repo_map, s.toolbox.scope.root)
        if not choices:
            s.frontend.emit(Info("I couldn't find an entry point. Try `/tour <file>`."))
            return None
        if len(choices) == 1:
            return choices[0]
        answer = await s.frontend.ask(
            AskChoice("Where should the tour start?", choices)
        )
        if answer.kind != "option" or not answer.option:
            return None
        return choices[answer.option - 1]

    async def _stop(self, path: str, came_from: str | None, number: int) -> None:
        s = self.session
        s.frontend.emit(Status(f"Stop {number}: {path}"))
        s.frontend.emit(Info(f"**Stop {number}** · `{path}`"))
        explained = await s._explain(
            "stop",
            prompts.stop_instructions(s._memory_context()),
            prompts.stop_prompt(path, came_from, number),
        )
        if explained is None:
            return
        outcome, report = explained
        summary = first_paragraph(outcome.text)
        if summary:
            s.toolbox.refresh(
                save_summary(s.tutor_dir, path, summary, s.recorder.now())
            )
            s.recorder.changes.append(f"{path}: summary saved")
        asked = await s._turn(
            "stop_question",
            prompts.STOP_QUESTION_INSTRUCTIONS,
            prompts.questions_prompt(
                path, report, s._snippets(report), label="The module"
            ),
            output_type=Question,
        )
        if asked.done is not None:
            await s._ask_all([asked.done.output])
